# Ansible variables for serverless URL shortener
# This file centralizes configuration for all playbooks

# AWS Configuration
aws_region: us-east-1
project_name: serverless-url-shortener
environment: prod

# Resource Names (consistent with Terraform and GitHub Actions)
lambda_functions:
  - shorten_url
  - redirect_url
  - options_handler

dynamodb_table_name: UrlTable
s3_bucket_name: yee-fei-url-shortener-frontend
iam_policy_name: url-shortener-lambda-enhanced

# Domain Configuration
domains:
  api: short.sctp-sandbox.com
  frontend: ui.sctp-sandbox.com

# CloudWatch Configuration
log_groups:
  - /aws/lambda/url-shortener-shorten
  - /aws/lambda/url-shortener-redirect
  - /aws/lambda/url-shortener-options

# X-Ray Configuration
xray_sampling_rule_name: url-shortener-sampling

# WAF Configuration
waf_web_acl_name: url-shortener-api-protection

# Deployment Configuration
deploy_timeout: 600  # 10 minutes
health_check_timeout: 30
health_check_retries: 3

# Monitoring Configuration
monitoring_retention_days: 7
alert_email: "" # Set this for notifications
